### ISSUE TITLE
Local development in docker.

### ISSUE THREAD

**Issue by EarthlingDavey** [nextauthjs/docs#104]
How do you feel about adding something like this to the repo README.md ?

I know it might seem like a waste of space, but to someone who uses docker for local development, it would be a real convenience.

1.  Create a docker volume for node_modules and start a nodeJS container.
```bash
$ docker volume create nextauthjs_docs_nm && \
docker run -it -w /app -v "$PWD":/app -p 3000:3000 \
--mount source=nextauthjs_docs_nm,target=/app/node_modules \
--name nextauthjs-docs --entrypoint /bin/ash \
node:16-alpine
```

3. If you're on an arm64/v8 (Apple M1 chip), npm will not find a compatible Chromium binary. Install it with apk.

```bash
$ apk add --no-cache chromium
```

4. Install dependencies.

```bash
$ npm install
```

5. Start the development server.

```bash
$ npm start -- --host 0.0.0.0
```

**Comment by balazsorban44** [comment]
Thank you for the idea, but I feel it is a bit unnecessary. Docs are just markdown files, we even provide ways to contribute without cloning the repo. There is an Edit button on every page that takes you to the online edit view where you can open a PR directly with your changes: 
![image](https://user-images.githubusercontent.com/18369201/140650841-5d80a75d-67b0-40f7-98b6-90fbe8415bb9.png)

I don't see many people contributing through Docker, to be honest. Most contributions so far are typo fixes or small rephrasing of sentences.

If someone needs that kind of help, we can now link them to this issue :slightly_smiling_face:

**Comment by EarthlingDavey** [comment]
OK sure thing..

I know we're both busy and this might not be the place to comment, but are you concerned about supply chain hacks? A single `npm install` can run an arbitrary script and render a development machine fully compromised. e.g. https://news.ycombinator.com/item?id=29122098

I think containerisation goes some way to combat that, that's the main reason I use nodes in docker.

**Comment by balazsorban44** [comment]
I'm not really afraid that the documentation with simple markdown files will be compromised to be honest. We also have reviews on every PR. Outside contributions are rare, and as said, mostly very minor fixes. I'll take our chances.

**Comment by EarthlingDavey** [comment]
You probably know though, it doesn't really work like that. It's not a targeted attack, the kind of project doesn't really matter. In the recent example, in case you had [rc](https://github.com/advisories/GHSA-g2q5-5433-rhrf) anywhere in your dependency tree, then ran npm install, then malware could be installed on the host.

I won't keep going on about this. I was sincerely curious about your position, and I felt responsible to tell you about it :)

**Comment by balazsorban44** [comment]
Thank you.

Unfortunately, I don't have a firm stand on the topic, I have never really heard about it before, to be honest. I also haven't seen similar projects requiring/recommending Docker to contribute to their docs pages. Maybe you have some examples I could look at?

What I understand is that Node/npm has some flaws compared to Deno in security as if I understand it correctly, Deno has security/opt-in permissions baked in. Hopefully, there is something to improve on the current ecosystem as well in the near future.

**Comment by EarthlingDavey** [comment]
I'll keep my eyes open for a good example. It's usually an option along-side commands for running directly on the host, and never really a recommendation or requirement. 

Yes, sure, I think Deno has it right, in secure by default. I'd also like to see some improvements with nodeJS, there is a petition at the moment for npm to at least make shell scripts on install opt-in.
