### ISSUE TITLE
VerificationToken db table name change not documented

### ISSUE THREAD

**Issue by anguskeatinge** [nextauthjs/docs#110]
### Title

VerificationToken db table name change not documented

### How to reproduce ☕️

n/a

### Your question/bug report 📓

I built a feature a while ago that generates a second verificationRequest for the email provider / mongodb adapter.
This allowed us to generate a fallback token in case AV software 'clicked' the link in the email and used up the verification token.

Anyway, I just spent 6 hours banging my head against the wall when the issue was just a collection name change from `verificationRequests` to `verification_tokens`. It would have been much faster if this was mentioned in the docs for the mongodb adapter.

### Contributing  🙌🏽

Yes, I am

**Comment by balazsorban44** [comment]
Hey, good to hear that you stopped banging your head! 🎉

Agreed, we can mention this in the migration guide under schema changes: https://next-auth.js.org/getting-started/upgrade-v4#schema-changes

feel free to open a PR!

_To be fair, the MongoDB Adapter is a new adapter not in v3 anyway, so technically the name hasn't changed, it never existed for that adapter :slightly_smiling_face:_

**Comment by anguskeatinge** [comment]
Just saw this thanks @balazsorban44
