### ISSUE TITLE
Unnecessary (?) docs page should not exist

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/docs#118]
I think this page is a remainder from v3.
https://next-auth.js.org/configuration/providers

See this discussion for context: https://github.com/nextauthjs/next-auth/discussions/3204

Should we delete it and fix the redirects?

**Comment by oxfist** [comment]
I’d love to contribute on this one! I see that in the current v4 docs there is no providers index page, at least from the navigation. Should this redirect to one of the providers pages or somewhere else?

**Comment by lluia** [comment]
@oxfist I think we can just delete the page, apart from the intro section, the content of the original page has been split in 3 pages in **v4** which is nicer for navigation. I would point existing links here https://next-auth.js.org/providers/overview.

**Comment by oxfist** [comment]
Since this was merged into `main`, I think it can be closed now 🙌🏼
