### ISSUE TITLE
Cannot redirect from credential providers authorize function to other page as suggested by documentation

### ISSUE THREAD

**Issue by Mikko-AM** [nextauthjs/docs#163]
### Description 🐜

Documentation about credential providers authorize function states that you can redirect with url to some other page:

```
        // If you return null or false then the credentials will be rejected
        return null
        // You can also Reject this callback with an Error or with a URL:
        // throw new Error('error message') // Redirect to error page
        // throw '/path/to/redirect'        // Redirect to a URL
```

however, according to code:

```
if (provider.type === "credentials" && method === "POST") {
    const credentials = body

    let user: User
    try {
      user = (await provider.authorize(credentials, {
        query,
        body,
        headers,
        method,
      })) as User
      if (!user) {
        return {
          status: 401,
          redirect: `${url}/error?${new URLSearchParams({
            error: "CredentialsSignin",
            provider: provider.id,
          })}`,
          cookies,
        }
      }
    } catch (error) {
      return {
        redirect: `${url}/error?error=${encodeURIComponent(
          (error as Error).message
        )}`,
        cookies,
      }
    }
```

it seems not to be true. It always redirects to error page. Maybe let authorize to return redirect as string like callbacks.

### Is this a bug in your own project?

No

### How to reproduce ☕️

Try to redirect from authorize.

### Environment 🖥

"next-auth": "^4.0.2"

### Contributing 🙌🏽

Yes,  I am willing to help solve this bug in a PR

**Comment by Mikko-AM** [comment]
What is correct way to do custom, localized, cognito login functionality, WITH possibility for user to either signup, signin  or do account recovery. Account recovery for example is 3 step process:
1. ask cognito to send cognito code to email
2. provide code + userid + new password to cognito
3. signin using new credentials
It would be nice to be able to redirect user to correct page after each step without doing double redirects.

It is maybe wrong to use sign in endpoint with custom flows to do all those operations, but at least that endpoint is probably more secure than using own api endpoints.

**Comment by balazsorban44** [comment]
Please open a discussion, this is a different case from the original post.
