### ISSUE TITLE
Confusion configuring FaunaDB Adapter

### ISSUE THREAD

**Issue by tatwater** [nextauthjs/docs#183]
Hello!

In the docs, the FaunaClient() constructor takes the `'http'` scheme and `'localhost'` domain on port `8443`. That causes a connection error without much in terms of Google search results that are helpful. However I found this [this](https://docs.fauna.com/fauna/current/learn/quick_start/client_quick_start?lang=javascript) page in Fauna's docs, and changed scheme to `'https'`, domain to `'db.fauna.com'`, and port to `443`. This works! But should I be routing through localhost somehow as a better practice? Why does the NextAuth documentation configure it the way it does?

Thanks so much!

**Comment by balazsorban44** [comment]
That's just an example. You should obviously configure the client to fit your needs.

**Comment by tatwater** [comment]
Very well, perhaps the example should be changed to reflect the default config from Fauna so as to be more helpful?
