### ISSUE TITLE
Cognito provider lacking information about setting custom scopes

### ISSUE THREAD

**Issue by l20DfX35JnKBfRn** [nextauthjs/docs#191]
The documentation is lacking information about setting custom scopes using the AWS cognito provider.

FYI: This is how we did it, now we get custom scopes within our JWT from AWS cognito.

Follow the standard procedure in the docs but add an additional authorization object to add scope parameters to the URL.

```js
CognitoProvider({
    clientId: 'client id',
      clientSecret: 'client secret',
      issuer: 'issuer url',
      idToken: true,
      authorization: {
              params: {
                scope: 'add custom scopes here'
              }
       }
 })
```

**Comment by balazsorban44** [comment]
There are multiple things in docs that show you how to do that:

https://next-auth.js.org/providers/cognito#options

https://next-auth.js.org/configuration/providers/oauth#options
