### ISSUE TITLE
Headers contain a zero width character

### ISSUE THREAD

**Issue by Myzel394** [nextauthjs/docs#196]
Copy any header which can create an anchor (https://next-auth.js.org/configuration/options with the header "NEXTAUTH_URL​" works guaranteed) and paste it into a zero width detector (WebStorm tells me that it's a `\u200B`).

**Comment by balazsorban44** [comment]
Not sure this is an actual _issue_. :shrug:

In any case, this should be posted on Docusaurus https://github.com/facebook/docusaurus
