### ISSUE TITLE
Update docs for Prisma Adapter

### ISSUE THREAD

**Issue by PedroHase** [nextauthjs/docs#24]
The [Prisma adapter doc](https://next-auth.js.org/adapters/prisma) has an old schema that does not work anymore (due to renaming of fields in the newer versions) which causes issues when trying to use Next-Auth with Prisma.

The README from https://github.com/nextauthjs/adapters/blob/e7a7690ca9e0b7e9af9d7456c908837c39a23611/packages/prisma/README.md seems to include the made changes. It would be great if the doc could be updated to have a correct schema that allows for easy integration with Prisma

**Comment by balazsorban44** [comment]
Not sure what you mean. The first link is the correct schema for the new version.

The second is the correct for the old one, available under https://next-auth.js.org/v3/adapters/prisma

**Comment by PedroHase** [comment]
Ah gotcha my bad. Still, wouldn't it be better then not to show the beta version of the docs as default? (also the banner will still be there when switching to V3)

**Comment by balazsorban44** [comment]
You get a significant warning on each site, which I would assume is enough to show you the version of the docs you are on, if the url didn't tell you already.

I don't think we can make the banner conditionally disappear, unfortunately.

![Screenshot_20210912-000428.png](https://user-images.githubusercontent.com/18369201/132962668-4cd1e02e-abd5-4e50-bc59-e4b42f2c2c98.png)
