### ISSUE TITLE
Example Prisma schema bug with Prisma 3.1.1

### ISSUE THREAD

**Issue by programbo** [nextauthjs/docs#46]
Small but painful bug in the [Prisma Adapter docs](https://github.com/nextauthjs/docs/blob/main/docs/adapters/prisma.md). The `VerificationToken` table does not allow tokens to be deleted when trying to sign in using the Email provider. The error message suggests setting `REPLICA IDENTITY` on the table. Pretty sure it's related to [Upgrade to Prisma 3 - Referential actions upgrade path](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3/referential-actions#checking-for-errors).

Simplest fix for me was to make the `token` field the primary key:

```prisma
model VerificationToken {
  identifier String
  token      String   @id // <- currently @unique
  expires    DateTime

  @@unique([identifier, token])
}

Related, Prisma 3.X the `referentialActions` option is no longer a preview feature.

 previewFeatures = ["referentialActions"] // deprecated

**Comment by balazsorban44** [comment]
Assuming I understood this correctly:
> table does not allow tokens to be deleted when trying to sign in using the Email provider.

I don't see any problems. Referential actions don't apply to VerificationToken, it is not in relation directly with either User, Account, or Session.

I just tested out the adapter locally with `3.1.1`, and had no issues with the schema that the docs suggest.

See the diagram here: https://next-auth.js.org/adapters/models

It would be more appropriate to open a bug report in https://github.com/nextauthjs/adapters/issues with a proper reproduction of your issue.
