### ISSUE TITLE
update `next-auth/jwt` import references

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/docs#61]
We no longer have a default export in `next-auth/jwt`, so this:

```ts
import jwt from "next-auth/jwt"
```

probably won't work anymore. This should be updated throughout the docs to:
```ts
import { getToken } from "next-auth/jwt"
```

We should also mention it in the migration docs in https://next-auth.js.org/getting-started/upgrade-v4

See https://github.com/nextauthjs/next-auth/issues/2896

**Comment by jason1985** [comment]
I'd like to try this if possible.

Thank you.

**Comment by balazsorban44** [comment]
Please do! Tell me if you need any help :slightly_smiling_face:
