### ISSUE TITLE
Document JWT changes

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/docs#87]
https://github.com/nextauthjs/next-auth/pull/3039 has removed some of the `jwt` options, this should be reflected in docs. Some places that come to mind:

- [x] https://next-auth.js.org/getting-started/upgrade-v4
- [ ] ~https://next-auth.js.org/faq#json-web-tokens~
- [x] https://next-auth.js.org/configuration/options#json-web-token-options
- [x] https://github.com/nextauthjs/next-auth#secure-by-default

**Comment by anthonyringoet** [comment]
I guess this can be closed as all the todo's are finished ✨
